### ISSUE TITLE
Pushing tag always fails

### ISSUE THREAD

**Issue by Neurrone** [anothrNick/github-tag-action#114]
[example failing run](https://github.com/Notarise-gov-sg/api-notarise-healthcerts/runs/2163161663?check_suite_focus=true)

```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/git#create-a-reference"
}
```

This is how the action is being called:

```
  create-new-tag:
    needs: test
    name: Create New Git Tag for release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: master
        DEFAULT_BUMP: patch
```
