### ISSUE TITLE
Is it possible to add additional commit when tagging?

### ISSUE THREAD

**Issue by billypchan** [anothrNick/github-tag-action#118]
Hi! I really like this action. My project currently using Jenkins to do the some task and thinking about replace it with github-tag-action. My question is it possible to add my custom commit when tagging? I need to update the version number of the project file. Currently I tried:
```
    - name: Bump version and push tag, dry run to get the next tag
      uses: anothrNick/github-tag-action@1.26.0
      id: dry_run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: develop
        DEFAULT_BUMP: patch
        DRY_RUN: true
        VERBOSE: true
        
    - name: update version.xcconfig
      run: |
        echo "new tag: '${{steps.dry_run.outputs.new_tag}}'"
        echo "tag: '${{steps.dry_run.outputs.tag}}'"
        ### process version.xcconfig
        git add .
        git commit -m"[skip ci] update version.xcconfig for '${{steps.dry_run.outputs.new_tag}}'" || true
        git push || true

    - name: Bump version and push tag, after version.xcconfig is updated
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: develop
        DEFAULT_BUMP: patch

```
