### ISSUE TITLE
Pre Release tag for branch

### ISSUE THREAD

**Issue by daveteu** [anothrNick/github-tag-action#119]
Newbie here (with git as well).

1) I'm expecting any merge/pull request on `master` branch to be tagged release (e.g. 1.0.1-release), and any pushed on to my `development` branch to be (e.g. 1.0.1-beta) **BUT** it's still showing 1.0.1 as my tag.

2) I also wish to have a -hotfix tag if I were to push to my `hotfix` branch. May I know how can I do it? All pushes to branch will be tag 1.0.1-hotfix

3) In my scenario should I set TAG_CONTEXT as branch instead of repo? Wouldn't there be countless bumping if I were to push hotfix -> merge development -> merge master (total of 3 bump)?

```
name: Bump version
on:
  push:
    branches:
      - master
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: false
        RELEASE_BRANCHES: master,development,hotfix.*

```

#### On another note
I don't quite understand why `pre_release` is false for the below build log.  Is this why my tags are not tagged with -beta?
```
Run anothrNick/github-tag-action@1.26.0
6
/usr/bin/docker run --name a33c13e3ee5d7cc5f4c4d9b323e6c3112d0e0_ad339a --label 8a33c1 --workdir /github/workspace --rm -e GITHUB_TOKEN -e WITH_V -e RELEASE_BRANCHES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/path":"/github/workspace" 8a33c1:3e3ee5d7cc5f4c4d9b323e6c3112d0e0
7
Is master a match for development
8
Is development a match for development
9
Is hotfix.* a match for development
10
pre_release = false
```

#### Yet anothr note
if I add #none in the commit message, shouldn't it not bump?

```
*** CONFIGURATION ***
9
	DEFAULT_BUMP: patch
10
	WITH_V: false
11
	RELEASE_BRANCHES: development*
12
	CUSTOM_TAG: 
13
	SOURCE: .
14
	DRY_RUN: false
15
	INITIAL_VERSION: 0.0.0
16
	TAG_CONTEXT: repo
17
	PRERELEASE_SUFFIX: beta
18
	VERBOSE: true
19
Is development* a match for development
20
pre_release = false
21
Update release branches for github actions #none
22
patch
23
Bumping tag 1.8.1. 
24
	New tag 1.8.2
25
2021-07-18T07:49:21Z: **pushing tag 1.8.2 to repo ****
```

Thank you in advance for all the help!
