### ISSUE TITLE
Auto-bumping with default commit regardless commit text

### ISSUE THREAD

**Issue by KonstantinKlepikov** [anothrNick/github-tag-action#137]
In description:

> Bump tag with minor version unless any commit message contains #major or #patch

i build this workflow:

  
```
name: release

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:

  create-build-push:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/anothrNick/github-tag-action
      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
```

In which commit should I leave the bump level? If I specify the bump level by #tag in the current commit in branch (not where pull request make), then on pull request a default bump occurs.
