### ISSUE TITLE
Action only bumps pre-minor versions in non-release branch

### ISSUE THREAD

**Issue by mdddev** [anothrNick/github-tag-action#142]
Hi,

pushing a change to the `dev` branch only triggers a pre-minor version change, e.g. v0.1.0-beta.5 to v0.1.0-beta.6. I tried including `#minor` in the commit message and my expectation would have been for the version to be v.0.2.0-beta1.

Is this how it is supposed to be? Or am I doing something wrong?

I'm using v1.36.0 of the action. Here is its log output:

```text
*** CONFIGURATION ***
	DEFAULT_BUMP: minor
	WITH_V: true
	RELEASE_BRANCHES: master,main
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: true
Is master a match for dev
Is main a match for dev
pre_release = true
fatal: ambiguous argument '0.0.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
test #minor dwfgregrg removedoutpoutsyml test32432 test3242 Merge pull request #1 from me/dev test32 test32 Update dotnet.yml Update dotnet.yml test3 test2 test test Create dotnet.yml init Initial commit
pre-minor
Bumping tag v0.1.0-beta.5. 
	New tag v0.1.0-beta.6
2022-04-05T06:38:32Z: **pushing tag v0.1.0-beta.6 to repo me/ghatest
  "ref": "refs/tags/v0.1.0-beta.6",
  "node_id": "REF_kwDOHH0ZAbdyZWZzL3RhZ3MvdjAuMS4wLWJldGEuNg",
  "url": "https://api.github.com/repos/me/ghatest/git/refs/tags/v0.1.0-beta.6",
  "object": {
    "sha": "d2386dd0ca[7](https://github.com/me/ghatest/runs/5828833973?check_suite_focus=true#step:4:7)50b943[8](https://github.com/me/ghatest/runs/5828833973?check_suite_focus=true#step:4:8)7deec0710b3cb[9](https://github.com/me/ghatest/runs/5828833973?check_suite_focus=true#step:4:9)011a1eaf",
    "type": "commit",
    "url": "https://api.github.com/repos/me/ghatest/git/commits/d2386dd0ca750b94387deec07[10](https://github.com/me/ghatest/runs/5828833973?check_suite_focus=true#step:4:10)b3cb90[11](https://github.com/me/ghatest/runs/5828833973?check_suite_focus=true#step:4:11)a1eaf"
  }
}
```

And here's the action yml

```yml
name: ci-dev

on:
  push:
    branches: [ dev ]
    paths: 
      - 'src/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        
    - name: Github Tag Bump
      id: semver
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: me
        WITH_V: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore /property:Version=${{steps.semver.outputs.tag}}
```
