### ISSUE TITLE
Can't use another action that is triggered on tags push

### ISSUE THREAD

**Issue by arunjoseph-tomtom** [anothrNick/github-tag-action#153]
I have another action that gets triggered on tags push

```
name: Create Releases

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
```
This action is not triggered by github-tag-action. But gets triggered when pushing a tag manually.
