### ISSUE TITLE
Error message: Resource not accessible by integration

### ISSUE THREAD

**Issue by hennihaus** [anothrNick/github-tag-action#154]
Hello together, I do not know how to fix this error. Has any of you an idea what is the reason? For a better view click on the picture.

![Bildschirmfoto 2022-04-29 um 20 29 59](https://user-images.githubusercontent.com/47771386/166003771-e5af371e-5149-4132-8992-b7caae97b561.png)

```
name: MongoDB CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        id: tag-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: false
          RELEASE_BRANCHES: master
          INITIAL_VERSION: 0.0.0

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ${{ github.repository }}:${{ steps.tag-version.outputs.new_tag }} --tag ${{ github.repository }}:latest

      - name: Push versioned Docker Image
        run: docker push ${{ github.repository }}:${{ steps.tag-version.outputs.new_tag }}

      - name: Push latest Docker Image
        run: docker push ${{ github.repository }}:latest
```
