### ISSUE TITLE
fatal: ambiguous argument 'multiple': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by michaeldimoudis** [anothrNick/github-tag-action#162]
I've used this before, but on a new project I can't workout why it is not working for me.

Getting this error: fatal: ambiguous argument 'multiple': unknown revision or path not in the working tree.

Do you know what could be the problem?

```
*** CONFIGURATION ***
	DEFAULT_BUMP: patch
	WITH_V: false
	RELEASE_BRANCHES: master,main
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: true
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: true
Is master a match for HEAD
Is main a match for HEAD
pre_release = true
fatal: ambiguous argument 'multiple': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'multiple': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by huwmartin** [comment]
We managed to resolve this by manually setting `RELEASE_BRANCHES` via env, i.e.

```
- id: semver_tag
   uses: anothrNick/github-tag-action@1.39.0
   env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEFAULT_BUMP: major
      RELEASE_BRANCHES: master
```
**and** manually pushing the first tag for `0.0.0` i.e. `git tag -a 0.0.0` and `git push origin 0.0.0`.

Not sure both of those are strictly necessary, it might just be pushing the tag that does it, and don't have a good sense as to why. Hope it helps.
