### ISSUE TITLE
Add option to add commit with bump

### ISSUE THREAD

**Issue by ksurl** [anothrNick/github-tag-action#204]
If there's a better way to do this, please let me know, but I have another workflow that triggers off pushes with tag to main. Since this just tags the latest commit, no pushes are detected so the other workflow doesn't run.

edit: actually this should have worked. When I manually tag and push, the 2nd workflow triggers. 

```
git push
git push --tags
```

```
on:
  push:
    branches:
      - main
    tags:
      - "*"
```

any idea why it is not running when tagged from this action?
