### ISSUE TITLE
Bug: commit messages with #major #minor or #patch are not working in the latest version

### ISSUE THREAD

**Issue by dgokcin** [anothrNick/github-tag-action#207]
Hello

I realized that commit messages with '#major' are not bumping versions. I am attaching my config below with some additional screenshots. I appreciate any guidance. Also If I directly commit to the develop or the main branch everything works but if I commit `#major` in a feature branch, it does not work, it applies the default bump. Is this a limitation?

Thanks

```yml
name: Bump Version
on:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        id: build
        run: dotnet build

      - name: Test with the dotnet CLI
        id: test
        run: |
          dotnet test --logger prettier \
          --logger trx --nologo --no-build \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover \
          /p:CopyLocalLockFileAssemblies=true \
          /p:UseSourceLink=true \
          -- xunit.parallelizeTestCollections=true

      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Unit Test Results # Name of the check run which will be created
          path: ./**/TestResults/*.trx # Path to test results
          reporter: dotnet-trx # Format of test results
          fail-on-error: "false" # Set action as failed if test report contains any failed test

  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Bump version and push tag
        if: github.ref == 'refs/heads/main'
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          VERBOSE: true

      - name: Bump version and push tag
        if: github.ref == 'refs/heads/develop'
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          PRERELEASE: true
          VERBOSE: true
```

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/33603535/196386656-dcf34e6b-c5f9-4188-8b3c-d02c22dd3a4f.png">
<img width="869" alt="image" src="https://user-images.githubusercontent.com/33603535/196386827-ab91b41c-717e-4763-95d3-33aaf8035999.png">
