### ISSUE TITLE
Push tag fails on schedule cron

### ISSUE THREAD

**Issue by danielceinos** [anothrNick/github-tag-action#22]
When I set the action trigger at push it works fine, but invoking it withing a cron the action fails with this error : `##[error]Docker run failed with exit code 6`

My workflow yml:
```
on: 
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: master
        DEFAULT_BUMP: patch
```
