### ISSUE TITLE
Attempting to tag builds on single branch

### ISSUE THREAD

**Issue by mcpierce** [anothrNick/github-tag-action#23]
What I'm trying to do is use this action to tag each push to our develop branch with an incremental build id so users can download artifacts on PR merge.

I've created a tag, **0.5.0-1**, and I have the following workflow definition (**github-actions-attempt-2** is my testing branch for now) checked in:
```
name: Tag commits on develop

on:
  push:
    branches:
      - develop
      - github-actions-attempt-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: build
          RELEASE_BRANCHES: develop,github-actions-attempt-2
```

I see the action run successfully, but I'm not seeing a new tag created, and when I look at the output for the action I'm seeing the help output from the semver script instead.

What is the proper **DEFAULT_BUMP** value to use and what format should our tags use to support bumping the build number only?
