### ISSUE TITLE
"$tag_commit" == "$commit" comparison for pre_tag

### ISSUE THREAD

**Issue by floriancircly** [anothrNick/github-tag-action#233]
If i run a GitHub actions workflow multiple times (with anothrNick/github-tag-action step v1.56) on the prerelease branch it always creates a new tag (but there is no new commit sha, just the new workflow run)

My parameters:
```
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          PRERELEASE_SUFFIX: dev
          PRERELEASE: true
          INITIAL_VERSION: 1.0.0
```
What I discovered in entrypoint.sh is that it checks if there is a difference within the tag_commit and the most recent commit (branch specific), but NOT the pre_tag. So it always creates a new tag if you run it in prerelase mode. In my opinion this should be intercepted, right?
```# get current commit hash for tag
tag_commit=$(git rev-list -n 1 "$tag")

# get current commit hash
commit=$(git rev-parse HEAD)

if [ "$tag_commit" == "$commit" ]
then
    echo "No new commits since previous tag. Skipping..."
    setOutput "new_tag" "$tag"
    setOutput "tag" "$tag"
    exit 0
fi```
