### ISSUE TITLE
Tagging on commits to a PR does not tag the commit

### ISSUE THREAD

**Issue by dalefrancis88** [anothrNick/github-tag-action#246]
I have it working fine with the tagging of a commit when merging to main but i want it to add a pre-relase tag for each commit on a PR.
When i use this to do that it creates this weird merge tag commit with two really long id's, i've never seen this before.

I'm guessing it's in how i'm configuring it and tried to change the properties for what branch it was using etc but nothing seems to work.
Do you have an example of tagging with pre-release on PR commits?

```
name: Bump version on pr changes

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']

    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.55.0 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        PRERELEASE: true
        DEFAULT_BRANCH: <<branch name>>
```

**Comment by sbe-arg** [comment]
Maybe relates to https://github.com/anothrNick/github-tag-action/issues/231 ?

Can you share some logs or screenshots of the tags you are getting? 
> When i use this to do that it creates this weird merge tag commit with two really long id's, i've never seen this before.

?? please share previous examples and workflow configs.

**Comment by sbe-arg** [comment]
I would probably do in the job:

```
jobs:
 job1:
  checkout:
    - uses: actions/checkout@v3
  pre_releases:
    - uses: anothrNick/github-tag-action@1.55.0
      if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: true
        PRERELEASE_SUFFIX: testing
```
that should each time you push to a branch that has a pr open get the latest latest latest tag x.x.x and branch it as x.x.x-testing.0 with each commit increasing .0, .1, so forth. once the pr is merged u get a bump to x.x.x + depending major, minor, patch.

If multiple prs are open U will get in trouble as all will compete for x.x.x-testing.X the testing.X is always competing.
the action does not currently support a pre release stream per branch.

if you do

PRERELEASE_SUFFIX: ${{ github.branch_ref}} or similar and you use any / _ - . in the branch names it will fail as is not semver valid hope it makes sense and good luck

or only do on: pull_request: opened and synchronize
unsure why you need pre-releases in the other events. the only event that reflect code changes are mainly sync and open is probably getting the first pre release
