### ISSUE TITLE
Update readme for pre-releases as the checkout needs ref: sha

### ISSUE THREAD

**Issue by sbe-arg** [anothrNick/github-tag-action#266]
in order for pre-release branch validation to work its needs to be clear that the workflow checkout requires the sha
```
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
```
non having the sha in some scenarios resolves to main, master with a the default `RELEASE_BRANCHES` array resulting in a always pre-release set to false
