### ISSUE TITLE
fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by karl-johan-grahn** [anothrNick/github-tag-action#273]
Something broke between version 1.62.0 and 1.66.0, after upgrading to that version and running the action on `main` branch with:

```yaml
      - name: Push Latest Tag
        uses: anothrNick/github-tag-action@1.66.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: ${{ inputs.RELEASE_BRANCH }}
```

we now get this error:

```sh
fatal: could not read Username for 'https://github.com/': No such device or address
```

We did not get this error when running the action on `main` branch in version 1.62.0.
