### ISSUE TITLE
fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by Grundmanis** [anothrNick/github-tag-action#278]
Was using this action with a public repository and it worked perfectly, changed repo to the `private` visibility and started to receive the following error: `fatal: could not read Username for 'https://github.com': No such device or address`

```
      - name: Push patch tag
        if: github.event.created != true
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

![Screenshot from 2023-07-27 15-37-09](https://github.com/anothrNick/github-tag-action/assets/6103997/46dee3d2-77ec-4384-b9aa-7b60c112de92)

**Comment by sbe-arg** [comment]
Set GIT_API_TAGGING false and permissions

**Comment by deefdragon** [comment]
Ive been trying to update to the latest version and have been running into this. I THINK I am running into issues because I have had persist-creds disabled? 

I managed, after much testing, to get things to function for this action by enabling it, but Im still in the process of determining if I can continue to use that persisted token, or if I must try something else (IE should it break my other actions)

**Comment by sbe-arg** [comment]
What is your action trigger?

**Comment by karl-johan-grahn** [comment]
I was getting the same error message for this flow and had to remove `persist-credentials: false` from the checkout step to make it work:

```yaml
name: Push

on:
  push:
    branches:
      - "main"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Had to remove this line, otherwise the push of tags didn't work
          fetch-depth: 0

      - name: Bump and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.<token> }}
          WITH_V: true
          DEFAULT_BUMP: patch
```
