### ISSUE TITLE
fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by Darjow** [anothrNick/github-tag-action#279]
Same error as: https://github.com/anothrNick/github-tag-action/issues/2787

```
jobs:
  RELEASE: 
    permissions:
      contents: write

    runs-on:
      - self-hosted

    steps: 
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        id: BUMP_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          GIT_API_TAGGING: false

```
