### ISSUE TITLE
How to configure github action file with Semantic Version Rules

### ISSUE THREAD

**Issue by qubetools** [anothrNick/github-tag-action#287]
First of all, I love this workflow, it works really good.

```yaml
    id: create-new-tag
    uses: anothrNick/github-tag-action@1.64.0
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WITH_V: true
      DEFAULT_BUMP: patch
```

I have above code in my main.yml file.
 I wanted to follow semantic versioning rules to bump version.
 
 For e.g 
 
1. If my message says
`fix: some message` or `fix(some scope): some message`
then it should trigger a patch version bump

2. If my message says
`feat: some message` or `feat(some scope): some message`
then it should trigger a minor version bump

Any idea how to configure it?
