### ISSUE TITLE
GitHub Actions Stickiness Major Tagging

### ISSUE THREAD

**Issue by paddyroddy** [anothrNick/github-tag-action#288]
Related to #280 (but think a more simple request).

I would like to bump my repo in the standard `minor` fashion, however I'd also like to update the `major` version (/create if it doesn't exist). This is the pattern used by various GitHub Actions (like `actions/checkout`).

So when I go from `v0.0.0` → `v0.0.1`, `v0` would now link `v0.0.1`. Then later one `v0.0.2` gets made, and `v0` now points to `v0.0.2`. At some point `v1.0.0` gets made, `v1` gets created and now points to `v1.0.0` etc. Thanks!

**Comment by sbe-arg** [comment]
Its definitely a feature request. In the meantime you can do it like this.

https://github.com/bridgecrewio/checkov-action/blob/master/.github/workflows/build.yml#L34

**Comment by paddyroddy** [comment]
Thanks! I got it working with this

```yaml
      - name: Extract major tag
        id: extract-major
        run: >-
          echo major_tag=$(echo ${{ steps.bump-version.outputs.new_tag }} |
          cut -d'.' -f1) >> $GITHUB_OUTPUT

      # this is done manually as need a non-annotated tag
      # TODO: replace with https://github.com/actions/publish-action
      - name: Update major tag
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag --force ${{ steps.extract-major.outputs.major_tag }} \
          ${{ steps.bump-version.outputs.new_tag }}
          git push origin ${{ steps.extract-major.outputs.major_tag }} --force
```
