### ISSUE TITLE
Images left from tagging

### ISSUE THREAD

**Issue by floriancircly** [anothrNick/github-tag-action#294]
Hi all.

After running the tagging job with anothrNick/github-tag-action I see a built docker image which seems a bit off because it always has the same container id and there is no obvious use for the image (after digging in the docker history I found out that the container originated from github-tag-action). Is the image necessary to create the tags and should I do the clean up manually?

```
jobs:
  Create_Tag:
    runs-on: [...]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          PRERELEASE_SUFFIX: dev
          PRERELEASE: true
          INITIAL_VERSION: 1.0.0
```

Thank you so much for your support!
