### ISSUE TITLE
can't get it to push tags to gitea

### ISSUE THREAD

**Issue by evanrich** [anothrNick/github-tag-action#301]
I think I'm doing everything right.  I have a workflow like this:

```
name: Semantic Release and Changelog
run-name: ${{ gitea.actor }} is running Semantic Release
on:
  push:
    branches:
      - 'master'

jobs:
  Patch:
    name: Patch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Minor version for each merge
      id: taggerDryRun
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}
        WITH_V: true
        DRY_RUN: true

    - name: echo new tag
      run: |
        echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"
    - name: echo tag
      run: |
        echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
    - name: echo part
      run: |
        echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"
  
  Build-and-Publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker
      run: curl -fsSL https://get.docker.com | sh

    - name: Build Docker image
      run: docker build -t harbor.server.com/library/my-docker-image:latest ./Docker/

    - name: Minor version for each merge
      id: taggerFinal
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}
        WITH_V: true
```

Everything runs fine, until it gets to the last step (Minor version for each merge).  It SEEMS to work, as this is what it says:
```
* [new branch]      add-networking-block -> origin/add-networking-block
 * [new branch]      dev                  -> origin/dev
 * [new branch]      pep8cleanup          -> origin/pep8cleanup
 * [new tag]         1.5.2                -> 1.5.2
 * [new tag]         1.6.10               -> 1.6.10
 * [new tag]         1.6.7                -> 1.6.7
 * [new tag]         1.6.8                -> 1.6.8
 * [new tag]         1.6.9                -> 1.6.9
 * [new tag]         v1.0.0               -> v1.0.0
 * [new tag]         v1.6.10              -> v1.6.10
 * [new tag]         v1.7.0               -> v1.7.0
 * [new tag]         v1.7.1               -> v1.7.1
 * [new tag]         v1.7.10              -> v1.7.10
 * [new tag]         v1.7.2               -> v1.7.2
 * [new tag]         v1.7.3               -> v1.7.3
 * [new tag]         v1.7.4               -> v1.7.4
 * [new tag]         v1.7.5               -> v1.7.5
 * [new tag]         v1.7.6               -> v1.7.6
 * [new tag]         v1.7.7               -> v1.7.7
 * [new tag]         v1.7.8               -> v1.7.8
 * [new tag]         v1.7.9               -> v1.7.9
History:
---
change secret name
---
Bumping tag v1.7.10 - New tag v1.8.0
EVENT: creating local tag v1.8.0
EVENT: pushing tag v1.8.0 to origin
2024-02-04T09:[32](https://git.server.com/user/my-docker-image/actions/runs/18/jobs/1#jobstep-4-32):[33](https://git.server.com/user/my-docker-image/actions/runs/18/jobs/1#jobstep-4-33)Z: **pushing tag v1.8.0 to repo ***/my-docker-image
```

but no new tag shows up in gitea, and the step fails with a red x.  The output just shows this:

```
| History:
| ---
| change secret name
| ---
| Bumping tag v1.7.10 - New tag v1.8.0
| EVENT: creating local tag v1.8.0
| EVENT: pushing tag v1.8.0 to origin
| 2024-02-04T09:32:33Z: **pushing tag v1.8.0 to repo ***/py-eagle-mqtt
[Semantic Release and Changelog/Build and Publish] [DEBUG] Return status: 6
[Semantic Release and Changelog/Build and Publish] failed to remove container: Error response from daemon: removal of container 83b0e286817adaa01147fe8cef2a8fa1a8329fcd683f440bb91e0810fc3ba5d3 is already in progress
[Semantic Release and Changelog/Build and Publish] [DEBUG] Removed container: 83b0e286817adaa01147fe8cef2a8fa1a8329fcd683f440bb91e0810fc3ba5d3
[Semantic Release and Changelog/Build and Publish]   ❌  Failure - Main Minor version for each merge
[Semantic Release and Changelog/Build and Publish]   ⚙  ::set-output:: old_tag=v1.7.10
[Semantic Release and Changelog/Build and Publish]   ⚙  ::set-output:: new_tag=v1.8.0
[Semantic Release and Changelog/Build and Publish]   ⚙  ::set-output:: part=minor
[Semantic Release and Changelog/Build and Publish]   ⚙  ::set-output:: tag=v1.8.0
[Semantic Release and Changelog/Build and Publish] exit with `FAILURE`: 6
[Semantic Release and Changelog/Build and Publish] [DEBUG] setupEnv => map[ACT:true ACTIONS_CACHE_URL:http://192.168.1.155:39325/ ACTIONS_RUNTIME_TOKEN:*** ACTIONS_RUNTIME_URL:https://git.server.com/api/actions_pipeline/ A_TEST_ENV_NAME_1:a_test_env_value_1 A_TEST_ENV_NAME_2:a_test_env_value_2 CI:true GITEA_ACTIONS:true GITEA_ACTIONS_RUNNER_VERSION:v0.2.6 GITHUB_ACTION:4 GITHUB_ACTIONS:true GITHUB_ACTION_PATH: GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:*** GITHUB_API_URL:https://git.server.com/api/v1 GITHUB_BASE_REF: GITHUB_EVENT_NAME:push GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL: GITHUB_HEAD_REF: GITHUB_JOB:Build-and-Publish GITHUB_REF:refs/heads/master GITHUB_REF_NAME:master GITHUB_REF_TYPE:branch GITHUB_REPOSITORY:***/py-eagle-mqtt GITHUB_REPOSITORY_OWNER:*** GITHUB_RETENTION_DAYS: GITHUB_RUN_ID:89 GITHUB_RUN_NUMBER:18 GITHUB_SERVER_URL:https://git.server.com GITHUB_SHA:a6d42086a76ec4294960a6f590879e95112e6c36 GITHUB_TOKEN:*** GITHUB_WORKFLOW:Semantic Release and Changelog GITHUB_WORKSPACE:/workspace/***/my-docker-image ImageOS:ubuntu20 JOB_CONTAINER_NAME:GITEA-ACTIONS-TASK-85_WORKFLOW-Semantic-Release-and-Changelog_JOB-Build-and-Publish RUNNER_PERFLOG:/dev/null RUNNER_TRACKING_ID:]
```

No reason as to the failure, just "failure 6"

Any ideas?
