### ISSUE TITLE
How to run for non-master branches

### ISSUE THREAD

**Issue by arcrank** [anothrNick/github-tag-action#302]
Hi,

I am trying to use this action in order to SerVer release to an sdk, but one where the overall main branch of the repo is not used, instead we merge to target language branches (i.e. java, python, go etc).

I tried a few different setups for this

earlier...
```
on:
  push:
    branches:
      - go
```

action
```
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor # Automatically bumps the minor version
          # For manual control, you can use commit message keywords, see action docs
          WITH_V: true
          RELEASE_BRANCHES: 'go'
```
knowing that I want to be able to go from a vX.Y.Z to a vX.Y+1.Z by default whenever there is a push (will be updated to PR) on the `go` branch here for example.

However, no tags are ever generated, I even tried to add extra step to echo the output here, and it is just empty.  Am I missing something here w.r.t to setting it up?
