### ISSUE TITLE
Empty History

### ISSUE THREAD

**Issue by Az-r-ow** [anothrNick/github-tag-action#306]
Hey, 

Every time I merge from a feature branch to main, it seems like this action is not picking up the history therefore not bumping the tag when it should. 

Here's the logs : 

```
*** CONFIGURATION ***
	DEFAULT_BUMP: none
	DEFAULT_BRANCH: main
	WITH_V: true
	RELEASE_BRANCHES: master,main
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	GIT_API_TAGGING: true
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE: false
	PRERELEASE_SUFFIX: beta
	VERBOSE: false
	MAJOR_STRING_TOKEN: major:
	MINOR_STRING_TOKEN: minor:
	PATCH_STRING_TOKEN: fix:
	NONE_STRING_TOKEN: #none
	BRANCH_HISTORY: compare
pre_release = false
From https://github.com/Az-r-ow/NeuralNet
 * [new branch]      callbacks       -> origin/callbacks
 * [new branch]      ci              -> origin/ci
 * [new branch]      clang-format    -> origin/clang-format
 * [new branch]      docs-automation -> origin/docs-automation
 * [new branch]      gh-pages        -> origin/gh-pages
 * [new branch]      major-refactor  -> origin/major-refactor
 * [new branch]      nf              -> origin/nf
 * [new branch]      revert-[24](https://github.com/Az-r-ow/NeuralNet/actions/runs/8222105189/job/22483220830#step:4:25)-ci    -> origin/revert-24-ci
 * [new branch]      serialization   -> origin/serialization
fatal: ambiguous argument 'v0.0.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
History:
---

---
Default bump was set to none. Skipping...
``` 

On this merge, I had a commit that started with "fix: " it didn't seem to pick it up. Here's how I configured the workflow. 
Also the reason why I'm using my github PAT (private access token) is because I also have a release workflow that will be triggered on tags push. 

```yml

name: Bump Version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  bump_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Bump Version and Push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          DEFAULT_BUMP: "none"
          GITHUB_TOKEN: ${{ secrets.PAT }}
          WITH_V: true
          MAJOR_STRING_TOKEN: "major:"
          MINOR_STRING_TOKEN: "minor:"
          PATCH_STRING_TOKEN: "fix:"
          BRANCH_HISTORY: "compare"
```

**Edit**

I downgraded the version of checkout to v3 and used the ref:  ${{ github.event.pull_request.merge_commit_sha}} 
It doesn't seem to resolve the problem.
