### ISSUE TITLE
doesn't bump if #none is contained in a previous commit message and the default version bump is not none

### ISSUE THREAD

**Issue by nyoungstudios** [anothrNick/github-tag-action#330]
Usage:
```yaml
- name: Bump version and push tag
  id: create-tag
  uses: anothrNick/github-tag-action@1.71.0
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    WITH_V: true
```

If I make a commit message `commit one #none`, then I expect no version bump to be made. This is what happens. However, if I make the next commit without a version bump message, `commit two`, I still expect this action to made the default version bump. Instead, this action doesn't make a version bump in this case because `#none` is still present in the previous commit message.

Is my explanation what should be expected? Or was this made on purpose?

In other words, I feel like the `log` variable should only be the last commit message:

https://github.com/anothrNick/github-tag-action/blob/f278d49d30cdd8775cc3e7dd00b5ee11686ee297/entrypoint.sh#L162

Here is my configuration:

```
*** CONFIGURATION ***
	DEFAULT_BUMP: minor
	DEFAULT_BRANCH: 
	WITH_V: true
	RELEASE_BRANCHES: master,main
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	GIT_API_TAGGING: true
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE: false
	PRERELEASE_SUFFIX: beta
	VERBOSE: false
	MAJOR_STRING_TOKEN: #major
	MINOR_STRING_TOKEN: #minor
	PATCH_STRING_TOKEN: #patch
	NONE_STRING_TOKEN: #none
	BRANCH_HISTORY: compare
	FORCE_WITHOUT_CHANGES: false
	FORCE_WITHOUT_CHANGES_PRE: false
	TAG_MESSAGE: 
pre_release = false
History:
---
commit two

commit one #none

---
```

**Comment by lawndoc** [comment]
This just caused an issue for me too. I'm willing to look into this and open a PR with a fix if I can figure it out. I have some other stuff to wrap up and then I'll take a look.

**Comment by meraj-kashi** [comment]
Same issue here. As @nyoungstudios pointed out, this is caused by how commit history is handled. Squash or rebase merges collapse the history into a single commit, leaving only the last commit message.

The fix is to configure the action to rely on the latest commit only by setting ` BRANCH_HISTORY: last.`

```
      - name: Bump version
        id: bump
        uses: anothrNick/github-tag-action@1.75.0
        env:
          BRANCH_HISTORY: last
```
