### ISSUE TITLE
Getting vv with new changes

### ISSUE THREAD

**Issue by rkATmsk** [anothrNick/github-tag-action#341]
Hi Team,

```
    - name: create pre release
      if: |
        (github.event_name == 'workflow_dispatch' && !startsWith(github.ref, 'refs/heads/release/'))
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: true
        DEFAULT_BUMP: ${{ inputs.bump || 'patch' }}
        TAG_CONTEXT: branch
```

copilot debug:

You are still getting tags like vv1.108.27-beta.0 because both WITH_V: true and your code logic are adding a v prefix.

Here’s why:

WITH_V: true sets tagPrefix="v"
TAG_PREFIX: false means the tagPrefix is not overwritten, so it remains "v"
When generating a pre-release, your code does:
`new="${tagPrefix}${new}-${suffix}.0"`

But new already includes the prefix, so you get vv...

**Comment by jvondracek-enetiqa-trading** [comment]
+1

also started encountering this issue with the following setting which worked previously:

```
      - name: Get the latest tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          PRERELEASE: true
```

**Comment by fanna-repowered** [comment]
+1 
Step has not been altered since last year
```
      - name: Generate and push GitHub tag
        id: github-tag
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch
          PRERELEASE: ${{ steps.set-prerelease-flag.outputs.is_prerelease == 'true' }}
```

See May 6th and May 16th:

![Image](https://github.com/user-attachments/assets/d4e7bb0c-449f-4a1b-b855-27c8201d855e)
