### ISSUE TITLE
Feature - CREATE_INITIAL_VERSION

### ISSUE THREAD

**Issue by Jared-Hinze** [anothrNick/github-tag-action#344]
Hello,

I may be missing something obvious, but I believe 've noticed when beginning with a brand new repo that has no pre-existing tags that this github action fails to create the INITIAL_VERSION specified as a tag of its own. Instead, it creates the next tag version after the INITIAL_VERSION. I think it would be nice to allow users to create that specified tag to reduce extra code in workflows to check and do these things through other actions or scripts.

Given a new repository with no branches and an action configured simply as:
```yaml
- name: AutoTagger
  id: tagger
  uses: anothrNick/github-tag-action@1.73.0
  env:
    INITIAL_VERSION: "1.0.0"
    TAG_PREFIX: v
```
your current code on line 136...
```sh
tag_commit=$(git rev-list -n 1 "$tag" || true )
```
...will produce the following error...
```txt
fatal: ambiguous argument 'v1.0.0': unknown revision or path not in the working tree.
```

I believe this would be the ideal location to create the `$tag`...
```sh
#pseudo-ish code
create_initial_version=${CREATE_INITIAL_VERSION:-true}
...
tag_commit=$(git rev-list -n 1 "$tag" || true )
if [ $? -ne 0 ] && create_initial_version && !dryrun
then
    <create and push $tag>
    exit 0
fi
```

Thoughts?
