### ISSUE TITLE
Not triggering the 'push-tags' event

### ISSUE THREAD

**Issue by tamipangadil** [anothrNick/github-tag-action#36]
I'm just confused about the phrase `Pushes tag to github` under **Workflow** section of your readme.

Once you push the lightweight tag, should it trigger the event `on: push: tags:` on Github actions too?

**Comment by samlown** [comment]
I think you're talking about chained workflows. This is not supported by Github Actions, and we also spent some time arriving at that conclusion! You can see it explained at the top of the documentation here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows

If you think about it, it makes sense, as it would be way too easy to create an infinite loop of actions.

**Comment by tamipangadil** [comment]
Yup! Chained workflows. I have also figured out when I went through their documentation. And I have tried listening to both `on:push:tags` and `on:create` and neither of them being triggered after pushing tags using this action.

Have you tried pushing an event through their API endpoint? (Maybe I'm just hopeful)

**Comment by urbaned121** [comment]
Hi, 
Im wondering how to achieve scenario similar to above for two different workflow files
First workflow:
```
name: Create Tag
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
        newTag: ${{steps.tagStep.outputs.tag}}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      id: tagStep
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        WITH_V: true
        PRERELEASE: false
        DEFAULT_BUMP: minor
        RELEASE_BRANCHES: main
        GIT_API_TAGGING: false
```

and right after the tag was created I wanted to run the second workflow: 

```
name: Docker image build and push on tag
on:
  push:
    tags:
      - '**'
  # workflow_run:
  #   workflows: [Create Tag]
  #   types:
  #     - completed

  workflow_dispatch:

jobs:
    docker-build-job:
        runs-on: ubuntu-latest
        env:
          IMAGE_TAGS: |
            type=ref,event=branch,enable=true
            type=semver,pattern={{raw}}
          TAGS_FLAVOR: |
            latest=true
            
        steps:
          - name: Checkout codebase
            uses: actions/checkout@v4

          # https://github.com/docker/setup-buildx-action
          - name: Setup Docker Buildx
            uses: docker/setup-buildx-action@v3
            with:
              platforms: linux/amd64,linux/arm64
            
          - name: Sync metadata (tags, labels) from GitHub to Docker for  image
            id: meta_build
            uses: docker/metadata-action@v5
            with:
              images: 
              tags: ${{ env.IMAGE_TAGS }}
              flavor: ${{ env.TAGS_FLAVOR }}
            
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
            
          - name: Build and push  image
            id: docker_build
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./Dockerfile
              platforms: linux/amd64,linux/arm64
              # For pull requests, we run the Docker build (to ensure no PR changes break the build),
              # but we ONLY do an image push to DockerHub if it's NOT a PR
              push: ${{ github.event_name != 'pull_request' }}
              # Use tags / labels provided by 'docker/metadata-action' above
              tags: ${{ steps.meta_build.outputs.tags }}
              labels: ${{ steps.meta_build.outputs.labels }}
              ```
My question is how to pass the newly created tag to Docker build workflow without merging workflows into multiple jobs of the same workflow... 
on:push:tags  obviously do not work. 
Thanks in advance for any suggestions!
