### ISSUE TITLE
Missing DRY_RUN feature

### ISSUE THREAD

**Issue by phish108** [anothrNick/github-tag-action#47]
Thanks for this nice little action. 

While it  does a good job, I find that the current version allows only to tag a commit but not to determine a new tag without actually tagging the commit.

However, when I want to tag a npm release, I need to update and commit the ```package.json``` beforehand. This would require to first create the new tag, do some extra steps that end with a commit and finally tag *that* additional commit.

In the workflow I would like to do something like this: 

```yml
steps: 
# ...
- uses: anothrNick/github-tag-action@1.17.3
   id: tagger
   env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     DRY_RUN: true
- run: npm version ${{ steps.tagger.outputs.new_tag }}
  if: steps.tagger.outputs.new_tag != ""
- use: some-fancy/commit-action@latest
  if: steps.tagger.outputs.new_tag != ""
  with:
    message: Version Bump
- uses: anothrNick/github-tag-action@1.17.3
  if: steps.tagger.outputs.new_tag != ""
   env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     WITH_V: true
# ...
```
