### ISSUE TITLE
action is not using checkout branch but GITHUB_REF of the workflow 

### ISSUE THREAD

**Issue by phish108** [anothrNick/github-tag-action#49]
Sometimes during workflow it is necessary to checkout master directly in order to complete a workflow. 
In these cases this tag action fails, because it uses the $GITHUB_REF environment variable and does not verify if this variable is actually the same as the checked out branch. 

In my case I run the following steps after a successful merge action: 

```yml
steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
  
      - uses: anothrNick/github-tag-action@1.18.0
        id: tagger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
```

Instead of tagging the latest version, the action complains that `This branch is not a release branch. Skipping the tag creation.`. Further up the action spits the following logs. 

```
Is master a match for refs/pull/45/merge
pre_release = true
```

However, at this part of the workflow the checked out branch is actually a release branch and not the ref-branch that triggered the workflow. 

Shouldn't the action use the checked out branch rather than relying on the information provided by github?
