### ISSUE TITLE
Issue with RELEASE_BRANCHES param

### ISSUE THREAD

**Issue by lukasburns** [anothrNick/github-tag-action#62]
Hi, great action btw,

i'm having an issue with the RELEASE_BRANCHES, it appears the regex its not comparing correctly with the name of the branch.
the branch name is `release/v1.0.0` for example

this is the current configuration
```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: minor
        INITIAL_VERSION: 1.0.1
        RELEASE_BRANCHES: release/*
```

in the logs of the action I see the following

```
Is release/* a match for HEAD
pre_release = true
fatal: could not read Username for 'https://github.com': No such device or address
```

and at the end
```
minor
v0.7.0-8668037
This branch is not a release branch. Skipping the tag creation.
```

Any ideas why it is not recognizing it as a release branch? 
thanks!!

**Comment by omeraplak** [comment]
@lukasburns Hi,
I've same issue. Have you any suggest?

**Comment by jefflinse** [comment]
@lukasburns @omeraplak What version of `actions/checkout` are you using in your workflows? I hit this same issue and was able to resolve it by upgrading from v1 to v2 of the `actions/checkout` GitHub Action.

```yaml
steps:
  - name: Check out source code
    uses: actions/checkout@v2
    with:
      fetch-depth: 0
```

With v1, calls to `git rev-parse --abbrev-ref HEAD` outputs `HEAD`. With v2, it outputs `master` (or whatever branch you've configured your workflow to run for).

**Comment by vincentrohde** [comment]
I am using `actions/checkout@v2`, but still have the same issue when doing a pull request with `feature/test-pull`

This is my workflow file

```
name: Github Tag Action Pull
on:
  pull_request:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: feature/*
          DEFAULT_BUMP: minor
```

The output from the workflow

```

*** CONFIGURATION ***
	DEFAULT_BUMP: minor
	WITH_V: true
	RELEASE_BRANCHES: feature/*
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: true
Is feature/* a match for HEAD
pre_release = true
Merge 4041fae3b7c5c41e081c320f4e88bde306df683d into eeaa6e63783b330c71042c95962c93f388242aa6 try to fix pre_release try to fix pre_release try to fix pre_release try to fix pre_release try to fix pre_release update RELEASE_BRANCHES to test pull tag bump add pull request tag bump test code
pre-minor
Bumping tag v0.2.0-beta.4. 
	New tag v0.2.0-beta.5
2021-08-30T18:41:58Z: **pushing tag v0.2.0-beta.5 to repo vincentrohde/harvest-dashboard
  "ref": "refs/tags/v0.2.0-beta.5",
  "node_id": "MDM6UmVmMjE0NDg2NDY3OnJlZnMvdGFncy92MC4yLjAtYmV0YS41",
  "url": "https://api.github.com/repos/vincentrohde/harvest-dashboard/git/refs/tags/v0.2.0-beta.5",
  "object": {
    "sha": "f27788ef7e0e3e456dc5e94e72af45ea35dc11f9",
    "type": "commit",
    "url": "https://api.github.com/repos/vincentrohde/harvest-dashboard/git/commits/f27788ef7e0e3e456dc5e94e72af45ea35dc11f9"
  }

```

The tag is handled as a pre_release, eventhough it shouldn't. 

This is my repositories workflow file:
https://github.com/vincentrohde/harvest-dashboard/blob/develop/.github/workflows/github-tag-action-pull.yml

This is the pull request:
https://github.com/vincentrohde/harvest-dashboard/pull/42
