### ISSUE TITLE
Does not trigger another workflow which uses on push tags to create a release

### ISSUE THREAD

**Issue by sivaprasad-kiranum** [anothrNick/github-tag-action#64]
I am creating a tag using this action.
And then I have another workflow which uses on push tag to get triggered to create the release, but the release workflow is not getting triggered.

```yaml
on:
  push:
    tags:
      - v*

jobs:
  create-release:
    if: github.event.base_ref == 'refs/heads/master'
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
```
