### ISSUE TITLE
FEAT: Option to name pre-releases with beta, alpha...

### ISSUE THREAD

**Issue by fermoya** [anothrNick/github-tag-action#75]
Hi, I've just started using this action and I love, thanks for open-source it.

I wanted to ask, is there a way you could support suffixes to the tags? I'd like to add an action on my release-candidate branch and have tags created like _1.0.0-alpha.1_, _1.0.0-beta.1_ or _1.0.0-rc.1_ and increment them on new pushes. At the moment, if the action is triggered as a `pre_release`, the tag is released as _1.0.0-8618ffc_, for instance.

**UPDATE**
Actually, no tag is created if it's a prerelease:
```
if $pre_release
then
    echo "This branch is not a release branch. Skipping the tag creation."
    exit 0
fi
```

**Comment by andrewbanchich** [comment]
This would be awesome! Also hoping for this.

**Comment by fermoya** [comment]
I've created [this pull-request](https://github.com/anothrNick/github-tag-action/pull/83). I've tested it in my own repo. So how I've set it is:
```
name: Bump version
on:
  push:
    branches: [ master, develop ]
jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        token: '${{ secrets.PERSONAL_TOKEN }}'

    - name: Bump version and push tag
      uses: fermoya/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        TAG_CONTEXT: branch
        DEFAULT_BUMP: none
        WITH_V: false
        PRERELEASE_SUFFIX: beta
```
So when merged into `develop`, then `$pre_release` is true and beta version is generated depending on the log key (major, minor, patch) and incremented (beta.1, beta.2, ...). When merged into `master`, `$pre_release` is false and production version is generated.

@andrewbanchich you can test it if you replace:
```
uses: anothrNick/github-tag-action@master
```
with:
```
uses: fermoya/github-tag-action@master
```
in the meantime this get reviewed and merged
