### ISSUE TITLE
Source doesn't seem to work

### ISSUE THREAD

**Issue by DevSecNinja** [anothrNick/github-tag-action#94]
Hi, thanks for this great GH action!

I'm having an issue with the SOURCE environment variable. I would like to copy only the relevant files to a release folder and release the folder contents. This should exclude folders like .github/ from the release ZIP.

````yaml
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Create Release Folder
        run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.vscode/' --exclude='scripts/' . ./release
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main,release.*,hotfix.*
          SOURCE: release
````

Source: https://medium.com/@Keithweaver_/zip-code-base-with-github-actions-for-releases-aca66f530dae

The outcome from this job is a ZIP file with all the file contents in it, including the folders such as .github/. I checked the release folder and it doesn't include the folders that I would like to exclude. Using `release` or `./release` does not make a difference.

Any idea what this could be?

Thanks!
